name: Build and Deploy to Azure VM

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t my-static-site:latest .

      - name: Save Docker image as tar in workspace
        run: |
          docker save my-static-site:latest -o my-static-site.tar
          ls -lh my-static-site.tar
          test -s my-static-site.tar
          chmod 777  my-static-site.tar

      - name: Copy image to Azure VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          source: "my-static-site.tar"
          target: "~/"

      - name: Deploy on Azure VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          script: |
            docker load -i my-static-site.tar
            docker stop static-site || true
            docker rm static-site || true
            docker run -d -p 8080:80 --name static-site my-static-site:latest 
